### PR TITLE
fix 'junit_type' referenced before assignment error

### LINKED ISSUE #143: UnboundLocalError: local variable 'junit_type' referenced before assignment
After some recent junit work I am getting an the below failure. 

The variable `junit_type` is not defined and we get error:

```
SBY 22:09:12 [mor1kx_dcache_prv] summary: Elapsed clock time [H:MM:SS (secs)]: 0:00:15 (15)
SBY 22:09:12 [mor1kx_dcache_prv] summary: Elapsed process time [H:MM:SS (secs)]: 0:00:05 (5)
SBY 22:09:12 [mor1kx_dcache_prv] summary: engine_0 (smtbmc) returned FAIL for basecase
SBY 22:09:12 [mor1kx_dcache_prv] summary: counterexample trace: mor1kx_dcache_prv/engine_0/trace.vcd
SBY 22:09:12 [mor1kx_dcache_prv] DONE (FAIL, rc=2)
Traceback (most recent call last):
  File "/home/arch/local/yosys/bin/sby", line 469, in <module>
    task_retcode = run_task(task)
  File "/home/arch/local/yosys/bin/sby", line 458, in run_task
    task.print_junit_result(f, junit_ts_name, junit_tc_name, junit_format_strict=False)
  File "/home/arch/local/yosys/bin/../share/yosys/python3/sby_core.py", line 791, in print_junit_result
    print(f'<failure type="{junit_type}" message="{self.status}" />', file=f)
UnboundLocalError: local variable 'junit_type' referenced before assignment
make: *** [Makefile:45: mor1kx_dcache] Error 1
make: Leaving directory '/home/arch/work/openrisc/local-cores/mor1kx/bench/formal'
```

_Originally posted by @stffrdhrn in https://github.com/YosysHQ/sby/pull/133#r830383648_

### PR DESCRIPTION
**Pull request by jix**
This fixes #143

### CODE REVIEW

**Comment by nakengelhardt** [comment]
OK yeah, I understand how that ended up there now.

The actual type of failure in this case is "unexpected result", as you'll only end up in this code path if the return status is not in the `expect` list, but there were no errors in running the build... maybe we should put in `type="EXPECT"` instead?

**Comment by jix** [comment]
I did not pay close attention to when exactly this happened, I can double check that tomorrow, but I also just noticed that independent of this change, that line causes an error if there's a syntax error in the sby file:
```
SBY 20:21:48 [test] ERROR: sby file syntax error: [engine]
SBY 20:21:48 [test] DONE (ERROR, rc=16)
Traceback (most recent call last):
  File "/home/jix/work/sby/sbysrc/sby.py", line 469, in <module>
    task_retcode = run_task(task)
  File "/home/jix/work/sby/sbysrc/sby.py", line 458, in run_task
    task.print_junit_result(f, junit_ts_name, junit_tc_name, junit_format_strict=False)
  File "/home/jix/work/sby/sbysrc/sby_core.py", line 817, in print_junit_result
    junit_type = "assert" if self.opt_mode in ["bmc", "prove"] else self.opt_mode
AttributeError: 'SbyTask' object has no attribute 'opt_mode'
```

**Comment by nakengelhardt** [comment]
Oh yeah, that's expected: there is no checking of the input file at all, so if you get anything wrong there it errors all over the place in cryptic ways. (Fixing that in general, and https://github.com/YosysHQ/sby/issues/81 specifically, has been on my to-do list for two years now...)

**Comment by nakengelhardt** [comment]
OK, I've looked into it more and I would prefer a different way of solving this, that incidentally also allows me to easily avoid the traceback above. I'm working on a new PR, but I've just unearthed another bug in the "expect" handling...

**Pull request closed without merging**
