### PR TITLE
Add color handling via click.style and click.echo

### PR DESCRIPTION
**Pull request by clairexen**
:rainbow: 

image

### CODE REVIEW

**Comment by mmicko** [comment]
When testing, I have noticed some non-colored lines in output, those were coming from :
https://github.com/YosysHQ/sby/blob/claire/click/sbysrc/sby.py#L181
https://github.com/YosysHQ/sby/blob/claire/click/sbysrc/sby.py#L571

**Review by mmicko — APPROVED** [review]
LGTM now. Thanks

**Comment by mmicko** [comment]
For each sby_mode file there is log line 
```
task.log(f"""engine_{engine_idx}: {" ".join(engine)}""")
```
Maybe that one should use magenta color for `engine_xxx` part ?

**Comment by lethalbit** [comment]
Is there any reason for using click rather than something such as [rich](https://github.com/Textualize/rich)? In my opinion it's in general better for output than click, and handling args with the `argsparse` package works just as well.

Just wondering.

**Pull request merged**
